
### Get All Platforms
GET {{host}}//api/Platforms/
Accept: application/json

### Get Platform By Id
GET {{host}}//api/Platforms/1
Accept: application/json


### Create Platform 
POST {{host}}//api/Platforms/
Accept: application/json
Content-Type: application/json

{
  "name": "Dot Net Framework",
  "publisher": "Microsoft",
  "cost": "your soul"
}